-- ============================================================
-- V1: Sequences para geração de IDs no Oracle
-- ============================================================

CREATE SEQUENCE SQ_USUARIO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_LEAD         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_AGENDAMENTO  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_INTERACAO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_NOTIFICACAO  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_RELATORIO_IA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
