-- ============================================================
-- V2: Criação das tabelas principais
-- ============================================================

CREATE TABLE USUARIO (
    ID        NUMBER(19) DEFAULT SQ_USUARIO.NEXTVAL NOT NULL,
    NOME      VARCHAR2(40 CHAR)  NOT NULL,
    EMAIL     VARCHAR2(40 CHAR)  NOT NULL,
    SENHA     VARCHAR2(80 CHAR)  NOT NULL,
    DOC       VARCHAR2(11 CHAR)  NOT NULL,
    TELEFONE  NUMBER(20),
    DATANASC  DATE               NOT NULL,
    ROLE      VARCHAR2(20 CHAR)  DEFAULT 'OPERADOR',
    CONSTRAINT PK_USUARIO  PRIMARY KEY (ID),
    CONSTRAINT UQ_USR_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_USR_DOC   UNIQUE (DOC)
);

CREATE TABLE LEAD (
    ID                       NUMBER(19) DEFAULT SQ_LEAD.NEXTVAL NOT NULL,
    NOME                     VARCHAR2(40 CHAR)  NOT NULL,
    TELEFONE                 NUMBER(20)         NOT NULL,
    EMAIL                    VARCHAR2(40 CHAR)  NOT NULL,
    CANAL_ORIGEM             VARCHAR2(40 CHAR),
    STATUS                   VARCHAR2(40 CHAR)  DEFAULT 'Novo',
    LEAD_SCORE               VARCHAR2(40 CHAR),
    PRIORIDADE               NUMBER(10),
    FATOR_URGENCIA           NUMBER(1) DEFAULT 0,
    FATOR_CANAL              VARCHAR2(30 CHAR),
    FATOR_TEMPO_SEM_RESPOSTA VARCHAR2(40 CHAR),
    FATOR_REAGENDAMENTO      DATE,
    OPERADOR_ID              NUMBER(19),
    PROCEDIMENTO_INTERESSE   VARCHAR2(40 CHAR),
    PLANO_SAUDE              VARCHAR2(40 CHAR),
    ULTIMO_CONTATO           DATE,
    CRIADO_EM                DATE,
    CONSTRAINT PK_LEAD      PRIMARY KEY (ID),
    CONSTRAINT UQ_LEAD_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_LEAD_OPER  FOREIGN KEY (OPERADOR_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE AGENDAMENTO (
    ID               NUMBER(19) DEFAULT SQ_AGENDAMENTO.NEXTVAL NOT NULL,
    LEAD_ID          NUMBER(19) NOT NULL,
    OPERADOR_ID      NUMBER(19) NOT NULL,
    PROCEDIMENTO     VARCHAR2(40 CHAR),
    DATA_HORA        TIMESTAMP,
    STATUS           VARCHAR2(40 CHAR) DEFAULT 'Pendente',
    LEMBRETE_ENVIADO NUMBER(1) DEFAULT 0,
    CRIADO_EM        DATE,
    CONSTRAINT PK_AGEND       PRIMARY KEY (ID),
    CONSTRAINT FK_AGEND_LEAD  FOREIGN KEY (LEAD_ID)     REFERENCES LEAD(ID),
    CONSTRAINT FK_AGEND_OPER  FOREIGN KEY (OPERADOR_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE INTERACAO (
    ID                NUMBER(19) DEFAULT SQ_INTERACAO.NEXTVAL NOT NULL,
    LEAD_ID           NUMBER(19) NOT NULL,
    OPERADOR_ID       NUMBER(19) NOT NULL,
    TIPO              VARCHAR2(40 CHAR),
    CONTEUDO          VARCHAR2(2000 CHAR),
    URGENCIA_DETECTADA NUMBER(1) DEFAULT 0,
    URGENCIA_NIVEL    VARCHAR2(20 CHAR) DEFAULT 'NORMAL',
    REALIZADO_EM      DATE,
    CONSTRAINT PK_INTER      PRIMARY KEY (ID),
    CONSTRAINT FK_INTER_LEAD FOREIGN KEY (LEAD_ID)     REFERENCES LEAD(ID),
    CONSTRAINT FK_INTER_OPER FOREIGN KEY (OPERADOR_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE NOTIFICACAO (
    ID              NUMBER(19) DEFAULT SQ_NOTIFICACAO.NEXTVAL NOT NULL,
    LEAD_ID         NUMBER(19) NOT NULL,
    OPERADOR_ID     NUMBER(19),
    MENSAGEM        VARCHAR2(200 CHAR),
    LEAD_NOME       VARCHAR2(40 CHAR),
    GERADO_POR_IA   NUMBER(1) DEFAULT 0,
    LIDA            NUMBER(1) DEFAULT 0,
    CRIADO_EM       DATE,
    CONSTRAINT PK_NOTIF      PRIMARY KEY (ID),
    CONSTRAINT FK_NOTIF_LEAD FOREIGN KEY (LEAD_ID)     REFERENCES LEAD(ID),
    CONSTRAINT FK_NOTIF_OPER FOREIGN KEY (OPERADOR_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE RELATORIO_IA (
    ID               NUMBER(19) DEFAULT SQ_RELATORIO_IA.NEXTVAL NOT NULL,
    DATA_REFERENCIA  DATE         NOT NULL,
    GERADO_EM        TIMESTAMP    NOT NULL,
    TOTAL_LEADS      NUMBER(10),
    LEADS_NOVOS      NUMBER(10),
    LEADS_CONVERTIDOS NUMBER(10),
    LEADS_URGENTES   NUMBER(10),
    TAXA_CONVERSAO   NUMBER(10,4),
    RESUMO_IA        CLOB,
    RECOMENDACOES_IA CLOB,
    CONSTRAINT PK_RELATORIO PRIMARY KEY (ID)
);
